# Generated by Django 3.2 on 2021-04-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=255)),
                ('applicants_id_number', models.IntegerField()),
                ('applicants_tag_number', models.CharField(max_length=255)),
                ('applicants_phone_number', models.CharField(max_length=255)),
                ('applicants_email', models.EmailField(max_length=254)),
                ('applicants_department', models.CharField(max_length=255)),
                ('applicants_vehicle_type', models.CharField(max_length=255)),
                ('applicants_car_reg_number', models.CharField(max_length=255)),
                ('applicants_log_book_number', models.CharField(max_length=255)),
                ('aplicants_duration', models.CharField(choices=[('TM', 'three months'), ('SM', 'six month'), ('OY', 'one year')], default='TM', max_length=2)),
                ('aplicants_status', models.CharField(choices=[('PD', 'pending'), ('AP', 'approved'), ('RJ', 'rejected')], default='PD', max_length=2)),
                ('application_send_date', models.DateTimeField(auto_now=True)),
                ('application_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
