# Generated by Django 3.2 on 2021-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='aplicants_duration',
            field=models.CharField(max_length=255),
        ),
    ]
