# Generated by Django 3.2 on 2021-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210506_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
