# Generated by Django 3.2 on 2021-04-15 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('id_number', models.IntegerField()),
                ('tag_number', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('AP', 'Application'), ('MT', 'Marketing'), ('ST', 'Security'), ('PK', 'Kaps')], default='AP', max_length=2)),
                ('residential_non_residential_organization', models.CharField(choices=[('RS', 'Residential'), ('NR', 'Non Residential')], default='RS', max_length=2)),
                ('governmental_non_govermental', models.CharField(choices=[('GR', 'Governmental'), ('NG', 'Non Governmental')], default='GR', max_length=2)),
                ('organization', models.CharField(choices=[('RESIDENTIAL_GOVERNMENTAL', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('RESIDENTIAL_NON_GOVERNMENTAL', (('vhs', 'VHS ape'), ('dvd', 'DVD'))), ('NON_RESIDENTIAL_NON_GOVERNMENTAL', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('NON_RESIDENTIAL_GOVERNMENTAL', (('vhs', 'VHS Tape'), ('dvd', 'DVD')))], default='AP', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
